myprotein/urls.py
from django.contrib import admin
from django.urls import path, include #include追加

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('photo.urls')),
]

photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('post/', views.CreatePhotoView.as_view(), name='post'),

    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
]

photo/models.py
from django.db import models

# Create your models here.

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):

    class Meta:

        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

photo/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from django.views.genetic import CreateView

from django.urls import reverse_lazy

from .forms import PhotoPostForm

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required

class IndexView(TemplateView):

    template_name = 'index.html'


@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):


    form_class = PhotoPostForm

    template_name = "post_photo.html"

    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):


        postdata = form.save(commit=False)

        postdata.user = self.request.user

        postdata.save()

        return super().form_valid(form)
    
class PostSuccessView(TemplateView):

    template_name = 'post_success.html'

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}{% endlock %}</title>   

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">お気に入りを見つけよう</h4>
          <p class="text-muted">
            誰でも参加できる写真投稿サイトです
            自分で撮影した写真ならなんでもオーケー！
            でも、カテゴリに属する写真に限ります。
            コメントもつけてください！
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">サインアップ</a></li>
            <li><a href="#" class="text-white">ログイン</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email_me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Photo Gallery</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  {% block contents %}{% endlock %}
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please a lot!</p>
  </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      
  </body>
</html>

photo/templates/index.html
{% extends 'base.html'%}
{% block title %}Photo Gallery{% endblock %}
{% block centents %}
{% include "photos_title.html" %}
{% include "photos_list.html" %}
{% endblock %}

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">UserName</small>
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>

photo/templates/photos_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています！
        </p>
        <p>
          {% if user.is_authenticated %}
            <a href="{% url 'photo:post' %}"
              class="btn btn-primary my-2">投稿する</a>
            <a herf="{% url 'accounts:logout' %}"
              class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
            <a href="{% url 'accounts:signup' %}"
              class="btn btn-primary my-2">今すぐサインアップ</a>
            <a href="{% url 'accounts:login' %}"
              class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section> 

photo/templates/post_photo.html
{% extends 'base.html' %}

{% block title %}Post{% endblock%}

    {% block contents %}

    <br>
    <div class="container">

        <div class="row">

            <div class="col offset-2">

                <form method="POST"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>カテゴリ</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>タイトル</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>コメント</th>
                            <td>{{ form.comment }}</td>
                        </tr>
                        <tr>
                            <th>画像1</th>
                            <td>{{ form.imagel }}</td>
                        </tr>
                        <tr>
                            <th>画像2</th>
                            <td>{{ form.image2 }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </dv>
        </dv>
    </dv>
    {% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

    {% block contents %}

    <br><br>
    <div class="container">

        <div class="row">

            <div class="col offset-2">
                <h4>投稿が完了しました!</h4>
            </dv>
        </dv>
    </dv>
    {% endblock%}